#!/usr/bin/env python3
"""Generate src/boot-logo-spans.inc (the FilmGate start-up screen).

Light background, navy/sky wordmark set in Jost Medium.  The picture is stored
as horizontal runs {y, x, width, level}; level 26..28 is an edge-smoothing
ramp that boot-logo.c maps to palette entries 117 (light), 104 (sky), 216 (navy).
Level 29 is flat sky blue.  The artwork block is centred on (360, 240).
Run:  python3 build_tools/generate_boot_logo.py [preview.png]
"""
from pathlib import Path
import sys
from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parents[1]
FONT = ROOT / "data" / "fonts" / "source" / "jost-medium.ttf"
OUT = ROOT / "src" / "boot-logo-spans.inc"
W, H, SS = 720, 480, 4          # screen and supersampling factor
TITLE_W = 540                    # width of "MAGIC LANTERN"

def text_mask(text, size, track):
    """Return a coverage image (L) for text with letter tracking, supersampled."""
    f = ImageFont.truetype(str(FONT), size * SS)
    adv = [f.getlength(c) + track * SS for c in text]
    width = int(sum(adv)) + 4 * SS
    img = Image.new("L", (width, int(size * 1.6) * SS), 0)
    d = ImageDraw.Draw(img)
    x = 2 * SS
    base = int(size * 1.2) * SS
    for c, a in zip(text, adv):
        d.text((x, base), c, font=f, fill=255, anchor="ls")
        x += a
    return img, f

def tight(img):
    box = img.getbbox()
    return img.crop(box)

def fit_title():
    lo, hi = 40, 140
    for size in range(lo, hi):
        img, _ = text_mask("MAGIC LANTERN", size, 3)
        if tight(img).width / SS > TITLE_W:
            return size - 1
    return hi

def main():
    size = fit_title()
    title = tight(text_mask("MAGIC LANTERN", size, 3)[0])
    # split colours: MAGIC navy, LANTERN sky
    full_w = title.width
    ma, _ = text_mask("MAGIC ", size, 3)
    split = int(ImageFont.truetype(str(FONT), size * SS).getlength("MAGIC ") + 3 * 6 * SS)
    sub = tight(text_mask("EOS M  ·  FILMGATE", 21, 6)[0])

    gap1, rule_h, gap2 = 34, 2, 30
    th, sh = title.height // SS, sub.height // SS
    block_h = th + gap1 + rule_h + gap2 + sh
    top = (H - block_h) // 2
    canvas = {}   # (x, y) -> level

    def put(mask, x0, y0, navy, xsplit=None):
        w, h = mask.width // SS, mask.height // SS
        small = mask.resize((w, h), Image.BOX)
        px = small.load()
        for y in range(h):
            for x in range(w):
                c = px[x, y] / 255.0
                if c < 0.15:
                    continue
                is_navy = navy if xsplit is None else (x * SS < xsplit)
                if is_navy:
                    lvl = 26 if c < 0.45 else 27 if c < 0.8 else 28
                else:
                    lvl = 26 if c < 0.5 else 29
                canvas[(x0 + x, y0 + y)] = lvl

    tx = (W - th * 0 - title.width // SS) // 2
    put(title, tx, top, True, xsplit=split - 0)
    ry = top + th + gap1
    rw = 520
    for y in range(ry, ry + rule_h):
        for x in range((W - rw) // 2, (W + rw) // 2):
            canvas[(x, y)] = 29
    sx = (W - sub.width // SS) // 2
    put(sub, sx, ry + rule_h + gap2, True)

    spans = []
    for y in range(H):
        xs = sorted(x for (x, yy) in canvas if yy == y)
        i = 0
        while i < len(xs):
            j = i
            while j + 1 < len(xs) and xs[j + 1] == xs[j] + 1 and canvas[(xs[j + 1], y)] == canvas[(xs[i], y)]:
                j += 1
            spans.append((y, xs[i], j - i + 1, canvas[(xs[i], y)]))
            i = j + 1
    with OUT.open("w") as fh:
        fh.write("/* FilmGate start-up screen (720x480), generated by build_tools/generate_boot_logo.py.\n"
                 " * Levels 26..28 = edge ramp (light, sky, navy); 29 = flat sky blue. */\n")
        fh.write("struct boot_logo_span { uint16_t y; uint16_t x; uint16_t width; uint8_t color; };\n\n")
        fh.write("static const struct boot_logo_span boot_logo_spans[] = {\n")
        for s in spans:
            fh.write("    { %d, %d, %d, %d },\n" % s)
        fh.write("};\n")
    ys = [k[1] for k in canvas]; xs = [k[0] for k in canvas]
    print("spans", len(spans), "ink x", min(xs), max(xs), "y", min(ys), max(ys),
          "centre", (min(xs)+max(xs))/2, (min(ys)+max(ys))/2)
    if len(sys.argv) > 1:
        rgb = {26: (190, 235, 240), 27: (45, 150, 205), 28: (45, 75, 130), 29: (45, 150, 205)}
        im = Image.new("RGB", (W, H), (255, 255, 255))
        d = ImageDraw.Draw(im)
        d.rectangle((0, 0, W, 47), fill=rgb[28]); d.rectangle((0, 432, W, H), fill=rgb[28])
        for (x, y), l in canvas.items():
            im.putpixel((x, y), rgb[l])
        im.save(sys.argv[1])

if __name__ == "__main__":
    main()
